Header header

# This message defines the control input for players of the mdmi guarding territory game
# It defines (in the inertial frame):
# ax: acceleration in x direction
# ay: acceleration in y direction
# h:  altitude

# We use the coordinate frames with the following convention:
#   x: forward
#   y: left
#   z: up

float64 ax                  # acceleration in x direction [m/s^2]
float64 ay                  # acceleration in y direction [m/s^2]
float64 h                   # altitude [m]